[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies.async-std]
version = "1.10.0"

[dependencies.actix-web]
version = "4.0.0-beta.19"

[dependencies.async-graphql]
version = "3.0.20"

[dependencies.async-graphql-actix-web]
version = "3.0.20"
